const users = [
  // {
  //   avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar1.png',
  //   username: 'allmie',
  //   userJob: '프론트엔드',
  //   learningDate: '6개월',
  //   userStack: ['#JAVA', '#서버', '#WEB', '#서버', '#WEB', '#서버'],
  //   joinDate: 210102,
  //   likeCount: 3,
  //   shortIntro: '안녕하세요1',
  // },
  {
    avartarImg: 'http://kawala.in/assets/global/images/avatars/avatar1.png',
    nickname: 'allmie',
    email: 'asd@naver.com',
    tel: '010-1234-5678',
    position: 'FE',
    positionLevel: '초보',
    availableLocation: '지역 무관',
    availableWeek: '주중/주말 모두 가능',
    availableTime: '오전 위주',
    interestSkills: ['#WEB', '#Javascript'],
    intro: '열심히 하겠습니다',
    portfolio: ['www.naver.com', 'www.google.com'],
    role: ['key1', 'key2'],
    join: ['1'],
    receivedLike: 9,
    token: 'Token',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    avartarImg: 'http://kawala.in/assets/global/images/avatars/avatar2.png',
    nickname: 'maru',
    email: 'qwe@naver.com',
    tel: '010-1234-5678',
    position: 'ios',
    positionLevel: '초보',
    availableLocation: '지역 무관',
    availableWeek: '주중/주말 모두 가능',
    availableTime: '오전 위주',
    interestSkills: ['#Java', '#C++'],
    intro: '열심히 하겠습니다',
    portfolio: ['www.naver.com', 'www.google.com'],
    role: ['key1', 'key2'],
    join: ['1'],
    receivedLike: 19,
    token: 'Token',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    avartarImg: 'http://kawala.in/assets/global/images/avatars/avatar3.png',
    nickname: 'Jack',
    email: 'zxc@naver.com',
    tel: '010-1234-5678',
    position: '안드로이드',
    positionLevel: '초보',
    availableLocation: '지역 무관',
    availableWeek: '주중/주말 모두 가능',
    availableTime: '오전 위주',
    interestSkills: ['#Java', '#Spring'],
    intro: '열심히 하겠습니다',
    portfolio: ['www.naver.com', 'www.google.com'],
    role: ['key1', 'key2'],
    join: ['1'],
    receivedLike: 9,
    token: 'Token',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default users;
