const users = [
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar1.png',
    username: 'allmie',
    userJob: '프론트엔드',
    learningDate: '6개월',
    userStack: ['#JAVA', '#서버', '#WEB', '#서버', '#WEB', '#서버'],
    joinDate: 210102,
    likeCount: 3,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar4.png',
    username: 'csww',
    userJob: '프론트엔드',
    learningDate: '6개월',
    userStack: ['#WEB', '#서버'],
    joinDate: 210302,
    likeCount: 5,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar6.png',
    username: 'bbc',
    userJob: '백엔드',
    learningDate: '6개월',
    userStack: ['#Django', '#서버', '#WEB', '#백엔드', '#NodeJS'],
    joinDate: 200102,
    likeCount: 0,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar9.png',
    username: 'mike',
    userJob: '프론트엔드',
    learningDate: '3년',
    userStack: [
      '#REACT',
      '#웹서버',
      '#프론트엔드',
      '#TYPESCRIPT',
      '#WEB',
      '#서버',
    ],
    joinDate: 210303,
    likeCount: 0,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar1.png',
    username: 'allmie',
    userJob: '프론트엔드',
    learningDate: '6개월',
    userStack: ['#JAVA', '#서버', '#WEB', '#서버', '#WEB', '#서버'],
    joinDate: 210123,
    likeCount: 11,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar4.png',
    username: 'csww',
    userJob: '프론트엔드',
    learningDate: '6개월',
    userStack: ['#JAVA', '#서버', '#WEB', '#서버', '#WEB', '#서버'],
    joinDate: 210211,
    likeCount: 22,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar6.png',
    username: 'bbc',
    userJob: '백엔드',
    learningDate: '6개월',
    userStack: ['#Django', '#서버', '#WEB', '#백엔드', '#NodeJS'],
    joinDate: 210401,
    likeCount: 43,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar9.png',
    username: 'mike',
    userJob: '프론트엔드',
    learningDate: '6개월',
    userStack: [
      '#REACT',
      '#웹서버',
      '#프론트엔드',
      '#TYPESCRIPT',
      '#WEB',
      '#서버',
    ],
    joinDate: 210402,
    likeCount: 31,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar1.png',
    username: 'allmie',
    userJob: '프론트엔드',
    learningDate: '6개월',
    userStack: ['#JAVA', '#서버', '#WEB', '#서버', '#WEB', '#서버'],
    joinDate: 210422,
    likeCount: 13,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar4.png',
    username: 'csww',
    userJob: '프론트엔드',
    learningDate: '1년',
    userStack: ['#JAVA', '#서버', '#WEB', '#서버', '#WEB', '#서버'],
    joinDate: 210311,
    likeCount: 26,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar6.png',
    username: 'bbc',
    userJob: '백엔드',
    learningDate: '6개월',
    userStack: ['#Django', '#서버', '#WEB', '#백엔드', '#NodeJS'],
    joinDate: 210228,
    likeCount: 0,
  },
  {
    avatarImg: 'http://kawala.in/assets/global/images/avatars/avatar9.png',
    username: 'mike',
    userJob: '프론트엔드',
    learningDate: '6개월',
    userStack: [
      '#REACT',
      '#웹서버',
      '#프론트엔드',
      '#TYPESCRIPT',
      '#WEB',
      '#서버',
    ],
    joinDate: 210102,
    likeCount: 0,
  },
];

export default users;
